export default [
  {
    storeName: "Gul Ahmed",
    address: "Dolmen Mall Clifton, Karachi, Pakistan",
    products: ["clothes", "bedding", "accessories"],
    location: { lat: 24.8139, lng: 67.0422 },
  },

  {
    storeName: "Gul Ahmed",
    address: "The Forum Mall, Karachi, Pakistan",
    products: ["clothes", "bedding", "accessories"],
    location: { lat: 24.8237, lng: 67.0347 },
  },

  {
    storeName: "Gul Ahmed",
    address: "LuckyOne Mall, Karachi, Pakistan",
    products: ["clothes", "bedding", "accessories", "footwear", "jewelry"],
    location: { lat: 24.9217, lng: 67.1019 },
  },

  {
    storeName: "Gul Ahmed",
    address: "Ocean Mall, Karachi, Pakistan",
    products: [
      "clothes",
      "bedding",
      "accessories",
      "footwear",
      "perfumes",
      "makeup",
    ],
    location: { lat: 24.8172, lng: 67.0517 },
  },

  {
    storeName: "Gul Ahmed",
    address: "Saima Mall, Karachi, Pakistan",
    products: [
      "clothes",
      "bedding",
      "accessories",
      "perfumes",
      "makeup",
      "footwear",
    ],
    location: { lat: 24.9097, lng: 67.0972 },
  },

  {
    storeName: "Khadi",
    address: "Dolmen Mall Clifton, Karachi, Pakistan",
    products: [
      "perfume",
      "clothes",
      "abaya",
      "beach wear",
      "cardigans",
      "dungarees",
      "evening dress",
      "fancy dress costume",
      "feather garment",
      "fur garment",
    ],
    location: { lat: 24.8139, lng: 67.0422 },
  },

  {
    storeName: "Khadi",
    address: "The Forum Mall, Karachi, Pakistan",
    products: [
      "perfume",
      "clothes",
      "abaya",
      "beach wear",
      "cardigans",
      "dungarees",
      "evening dress",
      "fancy dress costume",
      "feather garment",
      "fur garment",
      "jewelry",
    ],
    location: { lat: 24.8237, lng: 67.0347 },
  },

  {
    storeName: "Khadi",
    address: "LuckyOne Mall, Karachi, Pakistan",
    products: [
      "perfume",
      "clothes",
      "abaya",
      "beach wear",
      "cardigans",
      "dungarees",
      "evening dress",
      "fancy dress costume",
      "feather garment",
      "fur garment",
      "footwear",
      "makeup",
    ],
    location: { lat: 24.9217, lng: 67.1019 },
  },

  {
    storeName: "Khadi",
    address: "Ocean Mall, Karachi, Pakistan",
    products: [
      "perfume",
      "clothes",
      "abaya",
      "beach wear",
      "cardigans",
      "dungarees",
      "evening dress",
      "fancy dress costume",
      "feather garment",
      "fur garment",
      "jewelry",
    ],
    location: { lat: 24.8172, lng: 67.0517 },
  },
  {
    storeName: "Junaid Jamshed",
    address: "Dolmen Mall, Tariq Rd, PECHS, Karachi, Pakistan",
    products: [
      "kurtas",
      "shalwar kameez",
      "sherwanis",
      "waistcoats",
      "kurta shalwar",
      "unstitched fabric",
    ],
    location: { lat: 24.874559, lng: 67.0629067 },
  },
  {
    storeName: "Sana Safinaz",
    address: "Park Towers, Clifton, Karachi, Pakistan",
    products: [
      "formal wear",
      "casual wear",
      "pret wear",
      "bridal wear",
      "lawn",
      "chiffon",
    ],
    location: { lat: 24.808511, lng: 67.0421165 },
  },
  {
    storeName: "Junaid Jamshed",
    address: "Zamzama Blvd, Defence Housing Authority, Karachi, Pakistan",
    products: [
      "kurtas",
      "shalwar kameez",
      "sherwanis",
      "waistcoats",
      "kurta shalwar",
      "unstitched fabric",
    ],
    location: { lat: 24.810787, lng: 67.0397393 },
  },
  {
    storeName: "Sana Safinaz",
    address: "Lucky One Mall, Rashid Minhas Rd, Karachi, Pakistan",
    products: [
      "formal wear",
      "casual wear",
      "pret wear",
      "bridal wear",
      "lawn",
      "chiffon",
    ],
    location: { lat: 24.941908, lng: 67.1456135 },
  },
  {
    storeName: "Junaid Jamshed",
    address: "Lucky One Mall, Rashid Minhas Rd, Karachi, Pakistan",
    products: [
      "kurtas",
      "shalwar kameez",
      "sherwanis",
      "waistcoats",
      "kurta shalwar",
      "unstitched fabric",
    ],
    location: { lat: 24.942069, lng: 67.1460154 },
  },
  {
    storeName: "Zellbury",
    address: "Dolmen Mall Clifton, Karachi, Pakistan",
    products: [
      "kurtas",
      "shalwar kameez",
      "pants",
      "tops",
      "dresses",
      "scarves",
      "shawls",
      "handbags",
      "jewelry",
    ],
    location: { lat: 24.808899, lng: 67.0442012 },
  },
  {
    storeName: "Zellbury",
    address: "Lucky One Mall, Rashid Minhas Rd, Karachi, Pakistan",
    products: [
      "kurtas",
      "shalwar kameez",
      "pants",
      "tops",
      "dresses",
      "scarves",
      "shawls",
      "handbags",
      "jewelry",
    ],
    location: { lat: 24.942061, lng: 67.1457889 },
  },
  {
    storeName: "Zellbury",
    address: "Bahria Town Karachi, Karachi, Pakistan",
    products: [
      "kurtas",
      "shalwar kameez",
      "pants",
      "tops",
      "dresses",
      "scarves",
      "shawls",
      "handbags",
      "jewelry",
    ],
    location: { lat: 25.0053657, lng: 66.9719468 },
  },
];
